name: schedules
description: A powerful and flexible library for managing recurring events and schedules. With Schedules, you can easily define complex schedules, including recurring events with custom intervals, exceptions, and more. Whether you're building a calendar app, a task scheduler, or anything in between, Schedules has you covered.

version: 0.0.3
repository: https://github.com/andyhorn/schedules

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
